# Generated by Django 3.1.2 on 2020-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopweb', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='freatured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
