# Generated by Django 3.1.2 on 2020-11-26 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopweb', '0004_product_freatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Entry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
