# Generated by Django 3.1.2 on 2020-11-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopweb', '0005_product_entry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Entry_date',
            new_name='entrydate',
        ),
    ]
