# Generated by Django 3.1.2 on 2020-11-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopweb', '0006_auto_20201126_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='entrydate',
            new_name='entry',
        ),
    ]
